title: 'Organisational Assistance'
updated_by: da07ab4c-34e8-47d2-afe9-a33081c1f656
updated_at: 1602692864
blueprint: offerings
subheading: 'Bríd O'' Meara expertise in mental health and wellbeing programme development'
content: |
  Are you developing/revising your wellbeing programme?
  
  Do you want to include effective and relevant material on mental health and wellbeing?
  
  Do you want to consider mental health in light of Covid 19?
  
  Are you looking for a mental health project manager?
  
  With over three decades practicing in mental health in Ireland, Brid is committed to and highly accomplished in the empowerment of people experiencing mental health difficulties. Bríd brings a wealth of knowledge and expertise in mental health and clinical governance.
  
  Having developed mental health programmes and revised existing programmes, Bríd is excellent at explaining mental health concerns in an easily understandable way and can provide a wealth of information on looking after and normalising one’s mental health. Bríd is experienced in delivering mental wellbeing content relating to Covid 19.
  
  Bríd has managed a number of mental health projects, including leading the award winning project “Changing observation practice in an acute mental health setting” in Saint John of God Hospital. She developed, co-piloted and delivered Aware’s popular “Relative’s and Friends programme”. She has also project managed a number of smaller mental health projects.
image: stock/white-laptop-female-hand-note-pen-phone-desk-6471.jpg
