title: "Barbara O'Connell"
author: "Barbara O'Connell"
primary_organisation: 'Chief Executive Officer, Acquired Brian Injury Ireland'
content: "We had the pleasure of welcoming Bríd to speak to our team about wellness this summer. Her perspectives were insightful, relevant and refreshing, and her delivery was next to none. What Bríd offered our team is a set of practical skills that will support us all to promote and prioritise self-care; tools clearly crafted through Bríd's own lived experience and careful reflection. The feedback from staff has been overwhelmingly positive, and I believe that the knowledge we all gained will yield enormous benefits for months to come."
updated_by: da07ab4c-34e8-47d2-afe9-a33081c1f656
updated_at: 1759584779
blueprint: testimonial
