title: 'Claire Hayes'
author: 'Dr. Claire Hayes'
primary_organisation: 'Consultant Clinical Psychologist'
content: 'Bríd speaks about mental health with authority, confidence and compassion. She draws on her vast training and experience to inform, guide and support employers and employees in developing and maintaining mental health programmes, policies and procedures. Her depth of knowledge combined with her focus on respecting and caring for every individual makes her an expert in her field.'
updated_by: da07ab4c-34e8-47d2-afe9-a33081c1f656
updated_at: 1603468053
blueprint: testimonial
