title: 'Fiona Keegan'
author: 'Fiona Keegan'
primary_organisation: 'Chief Executive Officer, Brain Tumour Ireland'
content: "I had the pleasure of working with Bríd O'Meara on the design and delivery of training for our support group volunteers.  Her wealth of experience and attention to detail was exceptional and our volunteers felt valued and cared for throughout the process.  Bríd gave us the confidence and the tools to deliver a service we can be proud of"
updated_by: da07ab4c-34e8-47d2-afe9-a33081c1f656
updated_at: 1759584003
blueprint: testimonial
