title: 'Jeanne Salter'
author: 'Jeanne Salter'
organisation: 'Aware Support Line volunteer'
content: '&ldquo;I would like to thank you for your expert guidance and wisdom which you shared with volunteers on the Support Line training days and more recently on Zoom. I have valued enormously the way in which you have both shared your knowledge and understanding of all aspects of mental health with us as volunteers, coupled with your personal touch in your care and support for us as individuals&rdquo;'
updated_by: da07ab4c-34e8-47d2-afe9-a33081c1f656
updated_at: 1602905749
blueprint: testimonial
