title: 'Joan Wall'
author: 'Joan Wall'
primary_organisation: 'Interim CEO, Suicide or Survive'
content: '“ I’ve had the privilege of working closely with Brid in her role as Eden Manager for over 2 years. Brid brings exceptional clinical excellence and ensures the highest standards of safety and care for all participants. Her calm, consistent, and deeply professional approach reflects not only her deep understanding of the work, but also her remarkable knowledge and wisdom. She is an outstanding professional whose leadership and insight have greatly enhanced the work of the Eden Programme. Collaborating with her has been an enriching experience.”'
updated_by: da07ab4c-34e8-47d2-afe9-a33081c1f656
updated_at: 1764099665
blueprint: testimonial
