title: 'Julie Breen'
author: 'Julie Breen'
organisation: 'Professional Wellbeing Project Coordinator, Law Society of Ireland'
content: |
  We will definitely be asking Bríd to speak at the Law Society again! She recently presented to Law Society members on the impact Covid-19 is having on anxiety levels and mood. Her professionalism in teasing out and helping members understand what anxiety is, alongside providing practical tips on how they can manage their own anxiety, was greatly appreciated.
  
  Feedback from members was overwhelmingly positive. They enjoyed the way Bríd’s presentation was practical and clear, leaving members with simple take-aways and practices that they can try out throughout the day.
  
  Thanks Bríd. We wish you the best of luck and can't wait to have you back!
updated_by: da07ab4c-34e8-47d2-afe9-a33081c1f656
updated_at: 1603386883
blueprint: testimonial
