title: 'Keith Gaynor'
author: 'Dr Keith Gaynor'
organisation: 'Senior Clinical Psychologist, St John of God Hospital'
content: 'I have worked with Bríd O''Meara for over eight years. She brings a unique combination of passion, knowledge and organisational skills to the challenge of ensuring positive mental health for all people. To my mind, her understanding of what it takes for an organisation to be a practical force for good in mental health is exceptional.'
updated_by: da07ab4c-34e8-47d2-afe9-a33081c1f656
updated_at: 1603404817
blueprint: testimonial
