title: Service
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: header
        field:
          input_type: text
          display: Header
          type: text
          icon: text
          listable: hidden
      -
        handle: preview
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          display: Preview
          type: markdown
          icon: markdown
          listable: hidden
      -
        handle: content
        field:
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          display: Content
          type: markdown
          icon: markdown
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
            - 'unique_entry_value:{collection},{id},{site}'
      -
        handle: parent
        field:
          type: entries
          collections:
            - services
          max_items: 1
          listable: false
          localizable: true
